### ISSUE TITLE
Ability to modify WP directory path

### ISSUE THREAD

**Issue by johncobbs** [LowGravityPL/RaccoonWP#2]
Currently, WP is installed at /wordpress. What would be required to change that in my install to /wp? Thanks!

**Comment by kamilgrzegorczyk** [comment]
There are few find/replace edits needed to change it.

Files which have to be edited:
- composer.json
- .env
- RaccoonWP/RaccoonApp.php
- public/index.php

as this change may fit more people I will probably make it in upcoming release of the library.

**Comment by furai** [comment]
Changed from `public/wordpress` to `public/wp` in RaccoonWP `v1.2.0` (0923e3a08f6341db214917fe6d55b3e666db731d) .

If you want to update - update the main RaccconWP installation to the newest, remove old wrodpress folder and do `composer install`.
